### ISSUE TITLE
ability to change the storage using `react-native-mmkv`

### ISSUE THREAD

**Issue by ddikodroid** [KoreanThinker/react-native-use-persisted-state#2]

**Comment by KoreanThinker** [comment]
Thank you for leaving an issue.
I will try to make AsyncStorage and mmky selectable!

https://github.com/mrousavy/react-native-mmkv

**Comment by ddikodroid** [comment]
that would be great 🔥

**Comment by KoreanThinker** [comment]
It's already here... 
https://github.com/mrousavy/react-native-mmkv/blob/master/docs/HOOKS.md
